### PR TITLE
Added Windows testing in GitHub

### PR DESCRIPTION
**Pull request by zzambers**
Added Windows testing in GitHub

### CODE REVIEW

**Comment by judovana** [comment]
what about run.sh?  Should I prepare run.bat?-)

**Comment by zzambers** [comment]
@judovana I don't know, I have not tried to run run.sh on windows

**Comment by judovana** [comment]
My crystall ball is saying it will fail.  Its jsut an thinking, if it have sense. to elaborate on it,or jsu tto wait for it to fail on Adoptium runners. I doubt we wish to add cygwin layers here...

**Comment by zzambers** [comment]
I think it would probably work in Msys2 (but have not tried). However aqa-tests do not use run.sh script [1]. Windows issues hit by adoptium/aqa-tests should already be fixed [2].

[1] https://github.com/adoptium/aqa-tests/pull/4327/files
[2] https://github.com/adoptium/aqa-tests/issues/4336

**Comment by judovana** [comment]
Of course they dont use run.sh ! but run it as jtregs. SO the idea was to run it as jtregs. I do not enforce it, and may add some run.bat. But not sure if it is worthy. Actually am sure a bit it is not worthy.

**Comment by zzambers** [comment]
I am also not sure it is worth it. Also we already have jtreg testing on linux, so this should catch most problems. (`@modules`, list of classes or JDK8+ compatibility). There could theoretically be windows+jtreg specific problem, but I don't think it is much likely. Also in bat you would have difficulties with downloading and unpacking, I think. If we wanted for windows jtreg runner script, it would probably be easier to make run.sh work under cygwin/msys2. Took a little closer look and seems it would need some fixes (so that it would only supply windows compatible paths to java/jtreg). I think currently it is easier to use Makefile, if support for windows+jtreg is added in the future, we can then enable it as well.

**Comment by zzambers** [comment]
Also I would like to keep Makefile approach either way, as it is easier to inspect problems as output is printed directly into console. I case of jtreg we currently only see pass/fail... :/

**Comment by judovana** [comment]
I definitley agree on keepig makefiles around!
I know in bat the wget and ucpio will be an issue.. :(
Thanx for looking to  cygwin/msys2

**Pull request merged**
