### PR TITLE
Increase timeout for cryptotest/CryptoTest test

### PR DESCRIPTION
**Pull request by annaibm**
- Increased the timeout to 1800

related: https://github.com/eclipse-openj9/openj9/issues/19264

Signed-off-by: Anna Babu Palathingal <anna.bp@ibm.com>

### CODE REVIEW

**Comment by judovana** [comment]
Thanx! maybe it is considerable to adjust global timeout multiplier at https://github.com/rh-openjdk/CryptoTest/blob/master/run.sh#L136

Just in case such timeouts will multiply. Merging

**Comment by annaibm** [comment]
Thanks @judovana !

**Comment by llxia** [comment]
Thanks @judovana for promptly merging the PR.

**Comment by judovana** [comment]
Now it is fast... But Aqavit will soon operate over tags, so even such targeted PR may not do it to aqavit immediately. I ahve no issue to be tagging this as necessary, but whether aqavit will reuse that particular newest tag will be another pr in aqavit. But we are not yet there :)

**Pull request merged**
